#!/bin/sh

#zenity --question \
#--title="" \
#--text "Choose A or B" \
#--ok-label="B" \
#--cancel-label="A"

CHOICE1=$(zenity --list \
    --height=220 \
    --title="Shut Down" \
    --text="Would you like to?" \
    --radiolist \
    --column="" --column="Operation" \
    FALSE "Shutdown" \
    FALSE "Restart" \
    FALSE "Suspend")

case $CHOICE1 in

    "Shutdown")
        echo "shutdown..."
        #
        #
        (
echo "10" ; sleep 1
echo "# Shutting down daemons" ; sleep 1
echo "20" ; sleep 1
echo "# Saving state and config" ; sleep 1
echo "50" ; sleep 1
echo "This line will just be ignored" ; sleep 1
echo "75" ; sleep 1
echo "# Shutting down system" ; sleep 1
echo "100" ; sleep 1
shutdown now
) |
zenity --progress \
  --title="System Shut Down" \
  --text="Preparing to Shut Down..." \
  --percentage=0 \
  --auto-kill \
  --auto-close

if [ "$?" = -1 ] ; then
        zenity --error \
          --text="Shutdown error! If problem persists, contact tech support."
fi

        #
        #
        
    ;;

    "Restart")
        echo "restarting..."
        #
        #
        (
echo "10" ; sleep 1
echo "# Shutting down daemons" ; sleep 1
echo "20" ; sleep 1
echo "# Saving state and config" ; sleep 1
echo "50" ; sleep 1
echo "This line will just be ignored" ; sleep 1
echo "75" ; sleep 1
echo "# Rebooting system" ; sleep 1
echo "100" ; sleep 1
reboot
) |
zenity --progress \
  --title="System Reboot" \
  --text="Preparing to Reboot..." \
  --percentage=0 \
  --auto-kill \
  --auto-close

if [ "$?" = -1 ] ; then
        zenity --error \
          --text="Shutdown error! If problem persists, contact tech support."
fi

        #
        #
    ;;

    "Suspend")
        echo "suspend..."
        gnome-screensaver-command -l
    ;;
    
esac  






