#!/bin/bash
#Program Name: safelist
#
#
# This program rejects non-whitelist uuid's.
#
#

#[Configuration]
TMPLIST="/tmp/idlist.cfg" # Temporary list of connected device ID's.
SAFELIST="/home/usc/bin/safe.cfg" # Your whitelist. Keep in a private directory.
FIRST_RUN="ls /dev/disk/by-uuid/"
#[ERROR HANDLING]
# If safe.cfg does not exist then Guardian will generate a new whitelist
# for you. Keep in mind that any connected device will automatically be
# added to this list of trusted devices, so verify only devices you trust
# are connected the first time you run Guardian.
#
# For security purposes ensure safe.cfg is in your home directory and you
# are the only person with access to modify its contents.
if [ ! -f $SAFELIST ]; then
   $FIRST_RUN >> $SAFELIST
fi

#[Main]

LABELIST="ls /dev/disk/by-uuid/"

$LABELIST >> $TMPLIST

RES=`grep -F -v -f $SAFELIST $TMPLIST` #Compare connected ID's to safe.cfg

if [ -n "$RES" ]; then #If grep returns text on STDIN then a new device was located
    ID=`ls /dev/disk/by-uuid/ | grep "$RES"` #Identify unauthorized USB ID's
    
    #zenity --warning --text="The following unauthorized USB device(s) have been detected:" #"$ID"
    notify-send --app-name=Guardian --icon=error --category=Security \
    "The following unauthorized USB device(s) have been detected:" "$ID"
    
    echo "ERROR: Guardian detected the following unauthorized USB device(s):" >> /home/usc/bin/guardian.log
    echo "$ID" >> /home/usc/bin/guardian.log
    
    umount /dev/disk/by-uuid/"$ID"
    
fi

#[Remove temporary files]
if [ -f $TMPLIST ]; then
      rm -f $TMPLIST
      
fi

